server.port=8080
spring.application.name=pdf-report-service
# Dùng SQL Authentication (bỏ integratedSecurity)
spring.datasource.url=jdbc:sqlserver://NEMMM\\CNAMM;databaseName=SanBongBTL;encrypt=false;
spring.datasource.username=java_user
spring.datasource.password=P@ssw0rd123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl